- hosts: localhost
  become_user: "{{ lookup('env', 'USER') }}"
  vars:
    git_keys: ".ssh/"
    personal_key: ".ssh/id_rsa_pessoal"
    work_key: ".ssh/id_rsa_kyros"
    source_git_config: ".ssh/config"
    dest_key_personal: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_pessoal"
    dest_key_work: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_kyros"
    dest_git_config: "{{ lookup('env', 'HOME') }}/.ssh/config"
    dest_git_keys: "{{ lookup('env', 'HOME') }}/.ssh/"
    hosts: "hosts"

  tasks:
    - include_tasks: tasks/devtools.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/flatpaks.yml
    - include_tasks: tasks/nerdfont.yml
    - include_tasks: tasks/nvim-setup.yml
