- name: Install git
  ansible.builtin.package:
    name: git
    state: latest
  tags:
    - dev
  become: true
  ignore_errors: true

- name: Add hosts
  become: true
  become_user: root
  shell: cat {{ hosts }} >> /etc/hosts

- name: Install JetBrains Toolbox
  shell: curl -fsSL https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh | bash
  tags:
    - dev
  become: true
  ignore_errors: true

- name: Install sdkman
  shell: curl -s "https://get.sdkman.io" | bash
  tags:
    - dev
  become: true
  ignore_errors: true

- name: Install poetry
  shell: curl -sSL https://install.python-poetry.org | python3 -
  tags:
    - dev
  become: true
  ignore_errors: true

- name: Config poetry
  shell: echo 'export PATH="/home/luisb/.local/bin:$PATH"' >> ~/.bashrc

- name: Install pyenv
  shell: curl https://pyenv.run | bash
  tags:
    - dev
  become: true
  ignore_errors: true

- name: Install zsh
  become: true
  become_user: root
  ansible.builtin.package:
    name: zsh
    state: present
  tags:
    - dev
  ignore_errors: true

- name: Install zsh
  become: true
  ansible.builtin.package:
    name: zsh
    state: present
  tags:
    - dev
  ignore_errors: true

- name: Set zsh as default
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: true


- name: Install oh-my-zsh
  become: true
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - dev
  ignore_errors: true
