- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: "git@github.com:luiseduardobatista/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
  tags:
    - install
    - dotfiles
    - stow

- name: Stowdotfiles
  shell: cd {{ lookup('env', 'HOME') }}/dotfiles && ./ubuntu.sh
  become: true
  tags:
    - install
    - dotfiles
    - stow
