- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present
    method: user
  tags:
    - flatpak
  become: true
  ignore_errors: true

- name: Install flathub repo
  shell: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak
  become: true
  ignore_errors: true

- name: Install DBeaver Community flatpak
  community.general.flatpak:
    name: io.dbeaver.DBeaverCommunity
    state: present
    method: user
  tags:
    - flatpak
  ignore_errors: true

- name: Install Flatseal flatpak
  community.general.flatpak:
    name: com.github.tchx84.Flatseal
    state: present
    method: user
  tags:
    - flatpak
  ignore_errors: true

- name: Install Brave Browser flatpak
  community.general.flatpak:
    name: com.brave.Browser
    state: present
    method: user
  tags:
    - flatpak
  ignore_errors: true

- name: Instal insomnia flatpak
  community.general.flatpak:
    name: rest.insomnia.Insomnia
    state: present
    method: user
  tags:
    - flatpak
  ignore_errors: true
