- name: ensure fonts directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Check if JetBrainsMono font exists
  ansible.builtin.find:
    paths: "{{ lookup('env', 'HOME') }}/.fonts"
    patterns: "JetBrainsMono*Nerd*Font*Complete*"
  register: jetbrainsmono_exists

- name: Download JetBrainsMono if it does not exist
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip"
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes
  when: jetbrainsmono_exists.matched == 0

