- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
  ignore_errors: true

- name: Install gcc
  ansible.builtin.package:
    name: gcc
    state: present
  become: true

- name: Install xclip
  ansible.builtin.package:
    name: xclip
    state: present
  become: true

- name: Install ripgrep
  ansible.builtin.package:
    name: ripgrep
    state: present
  become: true

- name: Install fd
  ansible.builtin.package:
    name: fd-find
    state: present
  become: true

- name: Install neovim build dependencies
  ansible.builtin.package:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential
    state: present
  tags:
    - install
    - neovim
  become: true
  become_user: root

- name: Clone Neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && CMAKE_BUILD_TYPE=RelWithDebInfo && git checkout stable"
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && sudo make install"
  tags:
    - install
    - neovim

- name: Install nvm to install node for neovim plugins
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash"

- name: Update shell
  shell: source ~/.zshrc

- name: Install node for neovim plugins
  shell: "nvm install node"
 
