- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_git_keys }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh keys
  copy:
    src: "{{ git_keys }}"
    dest: "{{ dest_git_keys }}"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  ignore_errors: true
