- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_git_keys }}"
    mode: 0700
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh keys
  copy:
    src: "{{ git_keys }}"
    dest: "{{ dest_git_keys }}"
    mode: 0600
    owner: "{{ lookup('env', 'USER') }}"
  tags:
    - dotfiles
    - install
    - ssh

- name: Change ssh keys access level.
  shell: chmod 644 ~/.ssh/id_rsa_pessoal.pub ; chmod 644 ~/.ssh/id_rsa_kyros.pub
  tags:
    - dotfiles
    - install
    - ssh

- name: Start ssh agent.
  shell: eval "$(ssh-agent)"
  tags:
    - dotfiles
    - install
    - ssh

- name: Set authorized personal key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa_pessoal.pub') }}"
  ignore_errors: true

- name: Set authorized work key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa_kyros.pub') }}"
  ignore_errors: true
  
- name: Restart shell
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
  tags:
    - dotfiles
    - install
    - ssh


